index:
    path: /
    controller: App\Controller\MainController::index

secret_create:
    path: /secret
    controller: App\Controller\Secret\SecretCreateController::index

show_secrete:
    path: /secret/{secretId}
    controller: App\Controller\SecretShowController::index

privacy_page:
    path: /privacy
    controller: App\Controller\PrivacyController::index

terms_and_conditions_page:
    path: /terms_and_conditions
    controller: App\Controller\TermsAndConditionsController::index

