index:
    path: /
    controller: App\Controller\MainController::index

create_secrete:
    path: /secret
    controller: App\Controller\SecretController::create

show_secrete:
    path: /secret/{secretId}
    controller: App\Controller\SecretShowController::index