index:
    path: /
    controller: App\Controller\MainController::index

secret_create:
    path: /secret
    controller: App\Controller\Secret\SecretCreateController::index

secret_unveil_confirmation:
    path: /secret/{secretId}
    controller: App\Controller\Secret\SecretConfirmUnveilTheSecretController::execute

secret_unveil:
    path: /secret/{secretId}/unveil
    controller: App\Controller\Secret\SecretUnveilController::index

privacy_page:
    path: /privacy
    controller: App\Controller\PrivacyController::index

terms_and_conditions_page:
    path: /terms_and_conditions
    controller: App\Controller\TermsAndConditionsController::index

