<?php

namespace App\tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MainControllerTest  extends WebTestCase
{
    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    public function testMainPageMustReturn200HttpCode()
    {
        // Arrange
        $this->client->request('GET', '/');

        // Act
        $returnedStatusCode = $this->client->getResponse()->getStatusCode();

        // Assert
        $this->assertEquals(200, $returnedStatusCode);
    }

    public function testMainPageMustHaveCreateSecretApplication()
    {
        // Arrange
        $crawler = $this->client->request('GET', '/');

        // Act
        $isApplicationFound = $crawler->filter('form.secret')->count();

        // Assert
        $this->assertEquals(1, $isApplicationFound);
    }

    public function testWhenUsersCreateASecretTheMessageFieldIsRequired()
    {
        // Arrange
        $crawler = $this->client->request( 'GET', '/');

        // Act
        $amountLinkForShare = $crawler->filter('.message[required="required"]')->count();

        // Assert
        $this->assertEquals(1, $amountLinkForShare);
    }

}
