<?php

namespace App\tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MainControllerTest  extends WebTestCase
{
    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testMainPageMustReturn200HttpCode()
    {
        // Arrange
        $client = static::createClient();
        $client->request('GET', '/');

        // Act
        $returnedStatusCode = $client->getResponse()->getStatusCode();

        // Assert
        $this->assertEquals(200, $returnedStatusCode);
    }

    public function testMainPageMustHaveCreateSecretApplication()
    {
        // Arrange
        $client = static::createClient();
        $crawler = $client->request('GET', '/');

        // Act
        $isApplicationFound = $crawler->filter('form.secret')->count();

        // Assert
        $this->assertEquals(1, $isApplicationFound);

    }

}
